name: "Continues Integration"


on:
  push:
    branches:
    - master
    - dev


env:
  flutter-version: 3.35.5


jobs:
  windows-tests:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Enable NMake
      uses: ilammy/msvc-dev-cmd@v1.13.0

    - name: Build
      working-directory: Tests
      run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -G "Ninja" ..
          cmake --build . -j --config Release
          cmake --install . --config Release

    - name: Tests
      working-directory: Tests/build/bin
      run: .\Tests
          

  linux-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build
      working-directory: Tests
      run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -G "Ninja" ..
          cmake --build . -j --config Release
          cmake --install . --config Release

    - name: Tests
      working-directory: Tests/build/bin
      run: |
          export LD_LIBRARY_PATH=$(pwd):${LD_LIBRARY_PATH}
          ./Tests


  build-windows:
    needs: windows-tests
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
  
    - name: Enable NMake
      uses: ilammy/msvc-dev-cmd@v1.13.0
  
    - name: Install Flutter
      uses: subosito/flutter-action@v2.16.0
      with:
        channel: stable
        flutter-version: ${{ env.flutter-version }}
    
    - name: Build
      run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=bin -DWITH_CLIENTS=ON -G "Ninja" ..
          cmake --build . -j --config Release
          cmake --install . --config Release

    - name: Move apps
      shell: bash
      run: |
          mkdir windows
          mkdir android
          mv SyncWatchersClient/build/windows/x64/runner/release/* windows
          mv SyncWatchersClient/build/app/outputs/flutter-apk/app-release.apk android

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows
        path: build/bin

    - name: Upload Flutter apps
      uses: actions/upload-artifact@v4
      with:
        name: flutter
        path: |
            windows
            android
            
            
  build-linux:
    needs: linux-tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build
      run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=bin -G "Ninja" ..
          cmake --build . -j --config Release
          cmake --install . --config Release

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux
        path: build/bin
