name: "Continues Integration"


on:
  push:
    branches:
    - master
    - dev


jobs:
  windows-build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build
      run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=bin -G "Ninja" ..
          cmake --build . -j
          cmake --install .
