name: "Continuous Integration"

on:
  push:
    branches: [master, dev, client, server]


jobs:
  windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
  
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Enable NMake
      uses: ilammy/msvc-dev-cmd@v1.13.0
      
    - name: Build
      shell: bash
      run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON .. && cmake --build . --parallel $(nproc) --config Release --target install

    - name: Tests
      shell: bash
      run: |
          cd build/bin
          ./SyncWatchers.exe & sleep 1
          cd ../Tests
          dotnet test Tests.dll

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows
        path: build/bin


  linux:
    runs-on: ubuntu-latest
    container:
      image: lazypanda07/web_framework_dev:1.0.6

    steps:
    - uses: actions/checkout@v4
  
    - name: Build
      run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON .. && make install -j $(nproc)

    - name: Tests
      run: |
          cd build/bin
          export LD_LIBRARY_PATH=$(pwd):${LD_LIBRARY_PATH}
          ./SyncWatchers & sleep 1
          cd ../Tests
          dotnet test Tests.dll

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux
        path: build/bin
        